### PR TITLE
Requesting Code Review: Youtube Page

### PR DESCRIPTION
**Pull request by edieatha**
HTML & CSS

### CODE REVIEW

**Review by men32z — COMMENTED** [review]
## Pull request currently under review by Luis Preza (TSE).

Kindly exercise patience 🐱

**Review by men32z — CHANGES_REQUESTED** [review]
Hey @edieatha!

first of all, since is a collaborative project,  can I ask why are you doing this project alone?

## Good job on this project! 👍
There are still some changes 👇 you need to implement to approve this request 🔍

### Required changes 

- [x] The project has a descriptive README.md ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
- [ ] Pull Request has meaningful title and a short description ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

- [x] Check HTML markup with this validator https://validator.w3.org/#validate_by_upload.  ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/validation_requirement.png) from Pathwright)

- [x] Make sure you don't make CSS common mistakes ([article for support ](https://speckyboy.com/good-bad-css-practices)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) 
    - no repeating of the same rule
    - no ID selectors for multiple elements ( you could use css classes instead).
    - no `!import` overusing
    - no inefficient selectors
    - no inline styling

### For the next project.
- [ ] Commits are descriptive ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_commits.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

- [ ] Encourage the use of the [`<main>` tag](https://www.w3schools.com/tags/tag_main.asp) for the dominant content of the `<body>` of a document

**Comment by edieatha** [comment]
Hey @men32z 

This was a collaborative project I did with my partner. However, when we submitted a pull request of the repository created by my partner, only he was awarded "project complete" status, while for me I have had a "waiting for review" now for 3 days.

My partner was successfully repaired with another coding partner, so out of frustration, I created another repository on my GitHub and cloned the same project, generated a pull request.

If you are interested in reviewing the project on my partner's repository with my collaborations and commit please visit this link: https://github.com/MFahadUmer/Youtube-clone/pull/4

Please advise.

Otherwise, I will be glad to apply the changes suggested

**Comment by men32z** [comment]
Please, make all required changes and submit your request again! so we can approve your project 😀,  if you have this kind of problems again contact microverse support on dashboard.

**Comment by edieatha** [comment]
Hey @men32z,
I Am done with the suggested changes, please review. thanks...

**Comment by lekegitrepo** [comment]
### Hi @edieatha :clap: 
### You have done a good job of completing the required changes. This project is approved.

### Note: right section of the navbar suppose to contain at least three icons. Please always write a short and descriptive pull request comment. Writing HTML & CSS as the description of the pull request is not professional. As mention above please write a descriptive comment in your next project and update this one.

### Reviewed by: Temitayo Adeleke

**Review by lekegitrepo — APPROVED** [review]
### Status: Approved

**Pull request merged**
